---
# influx details
influx_bucket_name:   tigstack
influx_org_name:      home
influx_user_name:     jeremy
influx_ip_address:    monitoringvm #assumes tailscale hostname


# Enable monitors
monitor_system:         true
monitor_network:        true
monitor_zfs:            false
monitor_internet_speed: false
monitor_sanoid_snapshots: false
monitor_sanoid_health: false