- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes


- name: Import InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add InfluxDB repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu stable main' state=present

- name: Install packages with no config
  become: true
  become_user: root
  package:
    state: present
    name: "{{ item }}"
  loop:
    - telegraf
